### PR TITLE
Migrate 0_Source.R to R package

### PR DESCRIPTION
**Pull request by andrewgryan**
Quick win, add contents of `0_Source.R` to `R/`

## TODO
- [x] add package dependencies using devtools
- [x] create test suite

### CODE REVIEW

**Comment by andrewgryan** [comment]
The first thing I notice is that these functions are vector calculations that expect a data frame as input and strings to match up columns. It'd be better to throw away the column names and focus on the vector calculations, calling code can deal with data frame assignment

**Comment by andrewgryan** [comment]
This PR is ready for review. The "unit" tests are merely proof of execution tests, the scientific validity of the results or the questions they pose should be tidied up in future PRs

**Comment by andrewgryan** [comment]
Next steps, extract 2, 3b, 4b calculations into the `R/` directory and remove duplication for each "scenario", e.g. CAMS/EMEP/5 microgram concentration.

**Review by natalietf — APPROVED** [review]
All looks good to me :) haven't seen .rd files before... assuming they are just documentation?

**Comment by andrewgryan** [comment]
Correct! The `Rd` files are man pages and are auto-generated thankfully

**Pull request merged**
